import { createContext, useCallback, useContext, useMemo, useState } from 'react'
import { useUserAttendance } from './UserAttendanceContext'

const EmployeeContext = createContext(null)

const seedEmployees = [
  {
    id: 'EMP-1042',
    loginId: 'priya.nair',
    name: 'Priya Nair',
    role: 'Engineering Lead',
    department: 'Engineering',
    email: 'priya.nair@company.com',
    mobile: '+91 98765 43210',
    gender: 'Female',
    maritalStatus: 'Married',
    joiningDate: '2022-04-18',
    dob: '1994-01-16',
    address: 'Bengaluru, Karnataka',
    attendanceStatus: 'present',
    about: 'Leads platform engineering and mentors new hires.',
    skills: ['React', 'Node.js', 'System Design'],
    certifications: ['AWS Solutions Architect'],
    bank: {
      accountNumber: 'XXXXXX2104',
      bankName: 'HDFC Bank',
      ifsc: 'HDFC0001234',
      pan: 'ABCDE1234F',
      uan: '101234567890',
    },
    salary: {
      monthlyWage: 90000,
      workingDaysPerWeek: 5,
      standardAllowance: 5000,
      performanceBonus: 4000,
      lta: 2500,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-violet-500 to-fuchsia-600',
  },
  {
    id: 'EMP-2201',
    loginId: 'rahul.verma',
    name: 'Rahul Verma',
    role: 'Payroll Analyst',
    department: 'Finance',
    email: 'rahul.verma@company.com',
    mobile: '+91 91234 56780',
    gender: 'Male',
    maritalStatus: 'Single',
    joiningDate: '2023-01-10',
    dob: '1996-09-11',
    address: 'Pune, Maharashtra',
    attendanceStatus: 'leave',
    about: 'Handles month-end payroll checks and vendor payouts.',
    skills: ['Payroll', 'Excel', 'Compliance'],
    certifications: ['Certified Payroll Professional'],
    bank: {
      accountNumber: 'XXXXXX8790',
      bankName: 'ICICI Bank',
      ifsc: 'ICIC0002004',
      pan: 'PQRSV5689K',
      uan: '102345678901',
    },
    salary: {
      monthlyWage: 72000,
      workingDaysPerWeek: 5,
      standardAllowance: 4000,
      performanceBonus: 2000,
      lta: 2000,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-cyan-500 to-indigo-600',
  },
  {
    id: 'EMP-3310',
    loginId: 'ananya.sharma',
    name: 'Ananya Sharma',
    role: 'Product Designer',
    department: 'Product',
    email: 'ananya.sharma@company.com',
    mobile: '+91 99887 66554',
    gender: 'Female',
    maritalStatus: 'Single',
    joiningDate: '2024-05-02',
    dob: '1998-07-20',
    address: 'Hyderabad, Telangana',
    attendanceStatus: 'absent',
    about: 'Designs employee-facing payroll and HR experiences.',
    skills: ['Figma', 'UX Research', 'Design Systems'],
    certifications: ['Google UX Certificate'],
    bank: {
      accountNumber: '',
      bankName: '',
      ifsc: '',
      pan: 'LMNOP5544R',
      uan: '',
    },
    salary: {
      monthlyWage: 65000,
      workingDaysPerWeek: 5,
      standardAllowance: 3500,
      performanceBonus: 1500,
      lta: 1500,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-amber-500 to-orange-600',
  },
  {
    id: 'EMP-4415',
    loginId: 'vikram.singh',
    name: 'Vikram Singh',
    role: 'Backend Engineer',
    department: 'Engineering',
    email: 'vikram.singh@company.com',
    mobile: '+91 98220 22334',
    gender: 'Male',
    maritalStatus: 'Married',
    joiningDate: '2021-11-03',
    dob: '1992-12-02',
    address: 'Chennai, Tamil Nadu',
    attendanceStatus: 'present',
    about: 'Builds payroll APIs and core backend workflows.',
    skills: ['Node.js', 'PostgreSQL', 'Redis'],
    certifications: ['Oracle Java SE'],
    bank: {
      accountNumber: 'XXXXXX2241',
      bankName: 'Axis Bank',
      ifsc: 'UTIB0001452',
      pan: 'AAWPS7654N',
      uan: '103456789012',
    },
    salary: {
      monthlyWage: 84000,
      workingDaysPerWeek: 5,
      standardAllowance: 4500,
      performanceBonus: 3000,
      lta: 2000,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-sky-500 to-blue-700',
  },
  {
    id: 'EMP-5528',
    loginId: 'meera.iyer',
    name: 'Meera Iyer',
    role: 'HR Officer',
    department: 'Human Resources',
    email: 'meera.iyer@company.com',
    mobile: '+91 99001 23456',
    gender: 'Female',
    maritalStatus: 'Single',
    joiningDate: '2023-06-12',
    dob: '1997-03-19',
    address: 'Mumbai, Maharashtra',
    attendanceStatus: 'leave',
    about: 'Manages onboarding and employee policy workflows.',
    skills: ['Employee Relations', 'Hiring', 'HRMS'],
    certifications: ['SHRM-CP'],
    bank: {
      accountNumber: 'XXXXXX5482',
      bankName: 'State Bank of India',
      ifsc: 'SBIN0005678',
      pan: 'BGTPI4455P',
      uan: '104567890123',
    },
    salary: {
      monthlyWage: 68000,
      workingDaysPerWeek: 5,
      standardAllowance: 3500,
      performanceBonus: 1800,
      lta: 1500,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'EMP-6632',
    loginId: 'arjun.mehta',
    name: 'Arjun Mehta',
    role: 'Payroll Officer',
    department: 'Finance',
    email: 'arjun.mehta@company.com',
    mobile: '+91 97666 44551',
    gender: 'Male',
    maritalStatus: 'Single',
    joiningDate: '2022-09-05',
    dob: '1995-08-07',
    address: 'Noida, Uttar Pradesh',
    attendanceStatus: 'present',
    about: 'Owns payroll reconciliation and compliance reporting.',
    skills: ['Payroll', 'TDS', 'Excel'],
    certifications: ['Payroll Compliance Specialist'],
    bank: {
      accountNumber: 'XXXXXX9911',
      bankName: 'Kotak Mahindra Bank',
      ifsc: 'KKBK0003145',
      pan: 'CFQPM8765R',
      uan: '105678901234',
    },
    salary: {
      monthlyWage: 76000,
      workingDaysPerWeek: 5,
      standardAllowance: 4200,
      performanceBonus: 2200,
      lta: 1700,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-indigo-500 to-violet-700',
  },
  {
    id: 'EMP-7749',
    loginId: 'sneha.iyer',
    name: 'Sneha Iyer',
    role: 'QA Engineer',
    department: 'Quality',
    email: 'sneha.iyer@company.com',
    mobile: '+91 98700 77881',
    gender: 'Female',
    maritalStatus: 'Single',
    joiningDate: '2024-01-15',
    dob: '1999-04-28',
    address: 'Kochi, Kerala',
    attendanceStatus: 'absent',
    about: 'Validates HRMS releases and automates regression suites.',
    skills: ['Cypress', 'Playwright', 'API Testing'],
    certifications: ['ISTQB Foundation'],
    bank: {
      accountNumber: '',
      bankName: '',
      ifsc: '',
      pan: 'HJKPI9087U',
      uan: '',
    },
    salary: {
      monthlyWage: 62000,
      workingDaysPerWeek: 5,
      standardAllowance: 3000,
      performanceBonus: 1200,
      lta: 1200,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-rose-500 to-pink-700',
  },
  {
    id: 'EMP-8854',
    loginId: 'karan.malhotra',
    name: 'Karan Malhotra',
    role: 'Frontend Engineer',
    department: 'Engineering',
    email: 'karan.malhotra@company.com',
    mobile: '+91 98711 22009',
    gender: 'Male',
    maritalStatus: 'Single',
    joiningDate: '2023-03-14',
    dob: '1996-02-21',
    address: 'Delhi',
    attendanceStatus: 'present',
    about: 'Builds UI modules for payroll and employee workflows.',
    skills: ['React', 'Tailwind', 'TypeScript'],
    certifications: ['Meta Front-End Developer'],
    bank: {
      accountNumber: 'XXXXXX3210',
      bankName: 'HDFC Bank',
      ifsc: 'HDFC0008112',
      pan: 'DKLPM4451Q',
      uan: '106789012345',
    },
    salary: {
      monthlyWage: 70000,
      workingDaysPerWeek: 5,
      standardAllowance: 3500,
      performanceBonus: 2200,
      lta: 1500,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'EMP-9961',
    loginId: 'neha.kapoor',
    name: 'Neha Kapoor',
    role: 'Talent Partner',
    department: 'Human Resources',
    email: 'neha.kapoor@company.com',
    mobile: '+91 98990 33441',
    gender: 'Female',
    maritalStatus: 'Married',
    joiningDate: '2021-08-08',
    dob: '1993-11-12',
    address: 'Gurugram, Haryana',
    attendanceStatus: 'leave',
    about: 'Leads recruiting and employee engagement initiatives.',
    skills: ['Recruitment', 'People Ops', 'Interviewing'],
    certifications: ['LinkedIn Recruiter Expert'],
    bank: {
      accountNumber: 'XXXXXX7814',
      bankName: 'ICICI Bank',
      ifsc: 'ICIC0007789',
      pan: 'FGHPK5521P',
      uan: '107890123456',
    },
    salary: {
      monthlyWage: 74000,
      workingDaysPerWeek: 5,
      standardAllowance: 3900,
      performanceBonus: 2400,
      lta: 1800,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-fuchsia-500 to-rose-600',
  },
  {
    id: 'EMP-1073',
    loginId: 'rohit.bansal',
    name: 'Rohit Bansal',
    role: 'DevOps Engineer',
    department: 'Infrastructure',
    email: 'rohit.bansal@company.com',
    mobile: '+91 98112 77890',
    gender: 'Male',
    maritalStatus: 'Single',
    joiningDate: '2022-10-17',
    dob: '1995-05-03',
    address: 'Jaipur, Rajasthan',
    attendanceStatus: 'present',
    about: 'Automates deployments and cloud infrastructure reliability.',
    skills: ['AWS', 'Docker', 'Kubernetes'],
    certifications: ['AWS SysOps Administrator'],
    bank: {
      accountNumber: 'XXXXXX1198',
      bankName: 'Axis Bank',
      ifsc: 'UTIB0000419',
      pan: 'LMBPR4410R',
      uan: '108901234567',
    },
    salary: {
      monthlyWage: 88000,
      workingDaysPerWeek: 5,
      standardAllowance: 5000,
      performanceBonus: 4200,
      lta: 2500,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'EMP-1187',
    loginId: 'aisha.khan',
    name: 'Aisha Khan',
    role: 'Business Analyst',
    department: 'Operations',
    email: 'aisha.khan@company.com',
    mobile: '+91 97777 11008',
    gender: 'Female',
    maritalStatus: 'Single',
    joiningDate: '2024-02-01',
    dob: '1999-01-25',
    address: 'Lucknow, Uttar Pradesh',
    attendanceStatus: 'absent',
    about: 'Maps HR requirements into product-ready specifications.',
    skills: ['Analysis', 'Jira', 'Process Mapping'],
    certifications: ['CBAP Foundation'],
    bank: {
      accountNumber: 'XXXXXX4522',
      bankName: 'SBI',
      ifsc: 'SBIN0011223',
      pan: 'PQRAK2245T',
      uan: '109012345678',
    },
    salary: {
      monthlyWage: 63000,
      workingDaysPerWeek: 5,
      standardAllowance: 3200,
      performanceBonus: 1400,
      lta: 1200,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-amber-500 to-yellow-600',
  },
  {
    id: 'EMP-1299',
    loginId: 'saurabh.jain',
    name: 'Saurabh Jain',
    role: 'Data Engineer',
    department: 'Analytics',
    email: 'saurabh.jain@company.com',
    mobile: '+91 97654 33221',
    gender: 'Male',
    maritalStatus: 'Married',
    joiningDate: '2020-12-28',
    dob: '1991-07-14',
    address: 'Indore, Madhya Pradesh',
    attendanceStatus: 'present',
    about: 'Builds data pipelines powering reports and salary dashboards.',
    skills: ['Python', 'SQL', 'ETL'],
    certifications: ['Databricks Associate'],
    bank: {
      accountNumber: 'XXXXXX6677',
      bankName: 'Kotak Mahindra Bank',
      ifsc: 'KKBK0007654',
      pan: 'TRJPS6698A',
      uan: '110123456789',
    },
    salary: {
      monthlyWage: 91000,
      workingDaysPerWeek: 5,
      standardAllowance: 5200,
      performanceBonus: 4500,
      lta: 2800,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-indigo-500 to-violet-600',
  },
  {
    id: 'EMP-1307',
    loginId: 'pooja.shetty',
    name: 'Pooja Shetty',
    role: 'Support Specialist',
    department: 'Support',
    email: 'pooja.shetty@company.com',
    mobile: '+91 97555 66770',
    gender: 'Female',
    maritalStatus: 'Married',
    joiningDate: '2023-11-20',
    dob: '1994-06-09',
    address: 'Mysuru, Karnataka',
    attendanceStatus: 'leave',
    about: 'Handles internal employee support and HRMS issue triage.',
    skills: ['Customer Support', 'Documentation', 'Ticketing'],
    certifications: ['ITIL Foundation'],
    bank: {
      accountNumber: '',
      bankName: '',
      ifsc: '',
      pan: 'XCVPS8871M',
      uan: '',
    },
    salary: {
      monthlyWage: 56000,
      workingDaysPerWeek: 5,
      standardAllowance: 2500,
      performanceBonus: 1000,
      lta: 900,
      fixedAllowance: 0,
      basicPercent: 50,
      hraPercentOfBasic: 40,
      deductions: { pfEmployee: 0, pfEmployer: 0, professionalTax: 200 },
    },
    avatarColor: 'from-pink-500 to-rose-600',
  },
]

function recalcSalary(salary) {
  const monthlyWage = Number(salary.monthlyWage) || 0
  const basic = Math.round((monthlyWage * (Number(salary.basicPercent) || 0)) / 100)
  const hra = Math.round((basic * (Number(salary.hraPercentOfBasic) || 0)) / 100)
  const standardAllowance = Number(salary.standardAllowance) || 0
  const performanceBonus = Number(salary.performanceBonus) || 0
  const lta = Number(salary.lta) || 0
  const used = basic + hra + standardAllowance + performanceBonus + lta
  const fixedAllowance = Math.max(0, monthlyWage - used)

  const pfEmployee = Math.round(basic * 0.12)
  const pfEmployer = Math.round(basic * 0.12)
  const professionalTax = Number(salary.deductions?.professionalTax) || 200

  return {
    ...salary,
    monthlyWage,
    yearlyWage: monthlyWage * 12,
    components: {
      basic,
      hra,
      standardAllowance,
      performanceBonus,
      lta,
      fixedAllowance,
      total: basic + hra + standardAllowance + performanceBonus + lta + fixedAllowance,
    },
    deductions: { pfEmployee, pfEmployer, professionalTax },
  }
}

function hydrateEmployees(list) {
  return list.map((emp) => ({ ...emp, salary: recalcSalary(emp.salary) }))
}

export function EmployeeProvider({ children }) {
  const { user } = useUserAttendance()
  const [employees, setEmployees] = useState(() => hydrateEmployees(seedEmployees))
  const [selectedEmployeeId, setSelectedEmployeeId] = useState(seedEmployees[0].id)

  const currentUserEmployee = useMemo(() => {
    const byEmail = employees.find((e) => e.email.toLowerCase() === String(user.email).toLowerCase())
    return byEmail ?? employees[0]
  }, [employees, user.email])

  const selectedEmployee = useMemo(
    () => employees.find((e) => e.id === selectedEmployeeId) ?? employees[0],
    [employees, selectedEmployeeId],
  )

  const selectEmployee = useCallback((id) => setSelectedEmployeeId(id), [])

  const updateEmployee = useCallback((id, updater) => {
    setEmployees((prev) =>
      prev.map((emp) => {
        if (emp.id !== id) return emp
        const next = typeof updater === 'function' ? updater(emp) : { ...emp, ...updater }
        return { ...next, salary: recalcSalary(next.salary) }
      }),
    )
  }, [])

  const value = useMemo(
    () => ({
      employees,
      selectedEmployee,
      selectedEmployeeId,
      selectEmployee,
      updateEmployee,
      currentUserEmployee,
      currentUser: user,
      role: user.role,
    }),
    [employees, selectedEmployee, selectedEmployeeId, selectEmployee, updateEmployee, currentUserEmployee, user],
  )

  return <EmployeeContext.Provider value={value}>{children}</EmployeeContext.Provider>
}

export function useEmployees() {
  const ctx = useContext(EmployeeContext)
  if (!ctx) throw new Error('useEmployees must be used within EmployeeProvider')
  return ctx
}
